spring.application.name=shipment-service
server.port=8081

#  Database 
spring.datasource.url=jdbc:postgresql://localhost:5434/shipmentdb
spring.datasource.username=postgresuser
spring.datasource.password=postgrespw
spring.datasource.driver-class-name=org.postgresql.Driver

#  Hibernate / JPA 
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.properties.hibernate.default_schema=inventory
spring.jpa.show-sql=true

#  Kafka Consumer 
spring.kafka.bootstrap-servers=localhost:9092

# earliest: on first start, read ALL messages from the beginning of the topic
# This is important during development you won't miss events that arrived
# before the consumer started.
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Manual offset commit: we only commit after successfully writing to DB,
# so Kafka can redeliver if we crash mid-processing
spring.kafka.listener.ack-mode=manual

#  Topic 
kafka.topic.order-events=Order.events

#  Logging 
logging.level.com.example=DEBUG
