spring.application.name=order-service
server.port=8080

#  Database 
spring.datasource.url=jdbc:postgresql://localhost:5433/orderdb
spring.datasource.username=postgresuser
spring.datasource.password=postgrespw
spring.datasource.driver-class-name=org.postgresql.Driver

#  Hibernate / JPA 
# create-drop: drops and recreates schema on every start (good for learning)
# use "validate" in production
spring.jpa.hibernate.ddl-auto=create-drop
# always: run schema.sql even on non-embedded (PostgreSQL) databases
spring.sql.init.mode=always

# All tables go inside the "inventory" schema
spring.jpa.properties.hibernate.default_schema=inventory

# Show SQL in console so you can see exactly what gets persisted
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#  Logging 
logging.level.com.example=DEBUG
